org: intiluna
app: dh-geopython
service: aws-python-flask-dynamodb-api-project

frameworkVersion: '3'

custom:
  tableName: 'anuncios-table-${sls:stage}'
  wsgi:
    app: app.app
  # scripts:
  #   hooks:
  #     after:deploy:finalize: "python3 preload_db.py"

provider:
  name: aws
  runtime: python3.9
  region: eu-west-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [ AnunciosTable, Arn ]
            - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_MESSAGES_TABLE}"
  environment:
    ANUNCIOS_TABLE: ${self:custom.tableName}
    #viene de simple-chat
    DYNAMODB_MESSAGES_TABLE: simple-chat-messages

        

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - httpApi: '*'
  # get_messages:
  #   handler: handler.get_messages
  #   events:
  #     - http:
  #         path: /{chat_id}
  #         method: get
  #         request:
  #           parameters:
  #             paths:
  #               chat_id: true
  # send_message:
  #   handler: handler.send_message
  #   events:
  #     - http:
  #         path: /{chat_id}
  #         method: post
  #         request:
  #           parameters:
  #             paths:
  #               chat_id: true

plugins:
  - serverless-wsgi
  - serverless-python-requirements
  - serverless-plugin-scripts

resources:
  Resources:
    AnunciosTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: anuncioId
            AttributeType: S
        KeySchema:
          - AttributeName: anuncioId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.tableName}
    DynamoChatsMessagesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_MESSAGES_TABLE}
        AttributeDefinitions:
          - AttributeName: chat_id
            AttributeType: S
          - AttributeName: ts
            AttributeType: S
        KeySchema:
          - AttributeName: chat_id
            KeyType: HASH
          - AttributeName: ts
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST


